// SVG charts for the local GrainMaster training monitor.
const $=id=>document.getElementById(id);let autoScroll=true,busy=false,previewKey='';
const names={not_started:'Not started',gpu_preflight:'GPU preflight',smoke_training:'Initial training check',formal_training:'Training',retry_wait:'Waiting for automatic recovery',training_complete:'Training complete',failed:'Training failed',process_missing:'Training process stopped'};
function chart(id,rows,keys,fixed){const svg=$(id),ns='http://www.w3.org/2000/svg';svg.replaceChildren();function el(tag,attrs,text){const n=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;svg.append(n);return n}
if(!rows.length){el('text',{x:290,y:115,fill:'#738491','text-anchor':'middle'},'Curves appear after the first completed epoch');return}
const vals=rows.flatMap(r=>keys.map(k=>r[k])).filter(Number.isFinite),max=fixed||Math.max(.01,...vals)*1.12,xmax=Math.max(2,...rows.map(r=>r.epoch));
for(let i=0;i<=4;i++){const y=190-i*40;el('line',{x1:45,x2:560,y1:y,y2:y,stroke:'#e3e9ec'});el('text',{x:38,y:y+4,fill:'#738491','font-size':11,'text-anchor':'end'},(max*i/4).toFixed(2))}
keys.forEach((key,i)=>{const valid=rows.filter(r=>Number.isFinite(r[key])),color=i?'#bf8829':'#176e89';const points=valid.map(r=>`${45+(r.epoch-1)/(xmax-1)*515},${190-r[key]/max*160}`).join(' ');el('polyline',{points,fill:'none',stroke:color,'stroke-width':2.5});if(valid.length===1)el('circle',{cx:45,cy:190-valid[0][key]/max*160,r:3,fill:color})});el('text',{x:45,y:218,fill:'#738491','font-size':12},'Epoch 1');el('text',{x:560,y:218,fill:'#738491','text-anchor':'end','font-size':12},`Epoch ${xmax}`)}
function render(d){$('stage').textContent=names[d.stage]||d.stage;$('stage').classList.toggle('error',['failed','process_missing'].includes(d.stage));const p=d.progress;$('epoch').textContent=`Epoch ${p.epoch} / ${p.total}`;$('batch').textContent=p.batches?`Batch ${p.batch} / ${p.batches}`:'Waiting for batch log';$('fill').style.width=p.percent_of_maximum+'%';$('progress').setAttribute('aria-valuenow',p.percent_of_maximum.toFixed(2));$('progress').setAttribute('aria-valuemin','0');$('progress').setAttribute('aria-valuemax','100');$('completed').textContent=p.completed_epochs;$('gpu').textContent=d.gpu?.name||'—';$('memory').textContent=p.gpu_memory_gb!==null?`${p.gpu_memory_gb.toFixed(2)} GB`:'—';$('checkpoint').textContent=d.best_checkpoint_available?'best.pt saved':'Saved after first validation';const age=d.log_age_seconds;$('updated').textContent=age===null?'No log yet':`Log updated ${Math.round(age)} s ago`;
let warning=d.error||'';if(d.stage==='process_missing')warning='Training process not detected. Check the live log.';else if(d.stage==='retry_wait')warning=`Automatic recovery after ${d.retry_reason==='oom'?'out-of-memory':'stalled log'}: attempt ${d.retry_count}/${d.retry_limit}. Training will resume from the checkpoint.`;else if(d.log_stale)warning=`Training process ${d.process_alive===true?'is still running':'status is unconfirmed'}; the log has not updated for ${Math.round(age/60)} min. ${d.recovery_enabled?`Automatic recovery starts after ${Math.round(d.stall_timeout_seconds/60)} min without updates.`:'Training status needs inspection.'}`;else if(d.retry_count)warning=`This run has recovered automatically ${d.retry_count}/${d.retry_limit} time(s).`;if(d.process_alive===null&&!warning&&d.stage==='formal_training')warning='Training process status is temporarily unavailable; showing the latest log records.';if(d.memory_safe)warning=(warning?warning+' ':'')+'Memory-safe mode is active: chunked mask loss and gradient checkpointing.';$('warning').hidden=!warning;$('warning').textContent=warning;
const last=d.rows.at(-1)||{};$('loss').textContent=Number.isFinite(d.latest_losses.seg)?d.latest_losses.seg.toFixed(3):'—';$('ap').textContent=Number.isFinite(last['metrics/mAP50-95(M)'])?(last['metrics/mAP50-95(M)']*100).toFixed(1)+'%':'—';chart('lossChart',d.rows,['train/seg_loss','val/seg_loss']);chart('apChart',d.rows,['metrics/mAP50-95(M)','metrics/mAP50(M)'],1);
const scroll=$('log').scrollTop;$('log').textContent=d.lines.join('\n')||'No log yet';$('log').scrollTop=autoScroll?$('log').scrollHeight:scroll;$('dataset').replaceChildren();for(const[key,label]of [['train','Train'],['val','Validation'],['test','Test'],['review','Review pending']]){const span=document.createElement('span');span.textContent=`${label}: ${d.dataset[key]?.images??'—'} images / ${d.dataset[key]?.instances??'—'} instances`;$('dataset').append(span)}
const key=d.run_name+d.previews.join(',')+p.completed_epochs;if(key!==previewKey){previewKey=key;$('previews').replaceChildren();if(!d.previews.length){const text=document.createElement('p');text.textContent='Shown after the first validation epoch.';$('previews').append(text)}for(const name of d.previews){const a=document.createElement('a');a.href=`/api/training/preview/${name}?v=${p.completed_epochs}`;a.target='_blank';a.rel='noopener';const img=document.createElement('img');img.src=a.href;img.alt='Validation seed-mask prediction preview';a.append(img);$('previews').append(a)}}}
async function refresh(){if(busy)return;busy=true;try{const response=await fetch('/api/training',{cache:'no-store'});if(!response.ok)throw Error(response.status);render(await response.json());$('connection').textContent='Connected · updates every 5 s';$('connection').classList.remove('error')}catch(e){$('connection').textContent='Connection lost · retrying automatically';$('connection').classList.add('error')}finally{busy=false}}
$('pause').onclick=()=>{autoScroll=!autoScroll;$('pause').textContent=autoScroll?'Pause Scroll':'Resume Scroll'};$('refresh').onclick=refresh;refresh();setInterval(()=>{if(!document.hidden)refresh()},5000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});
